spring:
  application:
    name: joycenter

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.MySQLDialect}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID:?GOOGLE_ID is required}
            client-secret: ${GOOGLE_SECRET:?GOOGLE_SECRET is required}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: [ email, profile ]

          kakao:
            client-id: ${KAKAO_CLIENT_ID:?KAKAO_CLIENT_ID is required}
            client-secret: ${KAKAO_CLIENT_SECRET:?KAKAO_CLIENT_SECRET is required}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: [ account_email ]

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}


app:
  oauth:
    success-url: ${OAUTH_SUCCESS_URL:?OAUTH_SUCCESS_URL is required}
    failure-url: ${OAUTH_FAILURE_URL:?OAUTH_FAILURE_URL is required}

  cookie:
    secure: false
    same-site: Lax

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_STATIC}
    s3:
      bucket: ${AWS_BUCKET}

