server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DB_URL:?DB_URL is required}
    username: ${DB_USERNAME:?DB_USERNAME is required}
    password: ${DB_PASSWORD:?DB_PASSWORD is required}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  data:
    redis:
      host: ${REDIS_HOST:?REDIS_HOST is required}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}

jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}


logging:
  level:
    org.hibernate.SQL: info
